.TH "basicRfPktHdr_t" 3 "Sat Apr 30 2011" "Version 1.0" "Embedded GarageBand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
basicRfPktHdr_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint8\fP \fBpacketLength\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBfcf0\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBfcf1\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBseqNumber\fP"
.br
.ti -1c
.RI "\fBuint16\fP \fBpanId\fP"
.br
.ti -1c
.RI "\fBuint16\fP \fBdestAddr\fP"
.br
.ti -1c
.RI "\fBuint16\fP \fBsrcAddr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 110 of file basic_rf.c.
.SH "Field Documentation"
.PP 
.SS "\fBuint16\fP \fBbasicRfPktHdr_t.destAddr\fP"
.PP
Definition at line 116 of file basic_rf.c.
.SS "\fBuint8\fP \fBbasicRfPktHdr_t.fcf0\fP"
.PP
Definition at line 112 of file basic_rf.c.
.SS "\fBuint8\fP \fBbasicRfPktHdr_t.fcf1\fP"
.PP
Definition at line 113 of file basic_rf.c.
.SS "\fBuint8\fP \fBbasicRfPktHdr_t.packetLength\fP"
.PP
Definition at line 111 of file basic_rf.c.
.SS "\fBuint16\fP \fBbasicRfPktHdr_t.panId\fP"
.PP
Definition at line 115 of file basic_rf.c.
.SS "\fBuint8\fP \fBbasicRfPktHdr_t.seqNumber\fP"
.PP
Definition at line 114 of file basic_rf.c.
.SS "\fBuint16\fP \fBbasicRfPktHdr_t.srcAddr\fP"
.PP
Definition at line 117 of file basic_rf.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for Embedded GarageBand from the source code.
