.TH "basicRfCfg_t" 3 "Sat Apr 30 2011" "Version 1.0" "Embedded GarageBand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
basicRfCfg_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <basic_rf.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint16\fP \fBmyAddr\fP"
.br
.ti -1c
.RI "\fBuint16\fP \fBpanId\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBchannel\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBackRequest\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 62 of file basic_rf.h.
.SH "Field Documentation"
.PP 
.SS "\fBuint8\fP \fBbasicRfCfg_t.ackRequest\fP"
.PP
Definition at line 66 of file basic_rf.h.
.SS "\fBuint8\fP \fBbasicRfCfg_t.channel\fP"
.PP
Definition at line 65 of file basic_rf.h.
.SS "\fBuint16\fP \fBbasicRfCfg_t.myAddr\fP"
.PP
Definition at line 63 of file basic_rf.h.
.SS "\fBuint16\fP \fBbasicRfCfg_t.panId\fP"
.PP
Definition at line 64 of file basic_rf.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Embedded GarageBand from the source code.
