.TH "basicRfRxInfo_t" 3 "Sat Apr 30 2011" "Version 1.0" "Embedded GarageBand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
basicRfRxInfo_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint8\fP \fBseqNumber\fP"
.br
.ti -1c
.RI "\fBuint16\fP \fBsrcAddr\fP"
.br
.ti -1c
.RI "\fBuint16\fP \fBsrcPanId\fP"
.br
.ti -1c
.RI "\fBint8\fP \fBlength\fP"
.br
.ti -1c
.RI "\fBuint8\fP * \fBpPayload\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBackRequest\fP"
.br
.ti -1c
.RI "\fBint8\fP \fBrssi\fP"
.br
.ti -1c
.RI "volatile \fBuint8\fP \fBisReady\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBstatus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 88 of file basic_rf.c.
.SH "Field Documentation"
.PP 
.SS "\fBuint8\fP \fBbasicRfRxInfo_t.ackRequest\fP"
.PP
Definition at line 94 of file basic_rf.c.
.SS "volatile \fBuint8\fP \fBbasicRfRxInfo_t.isReady\fP"
.PP
Definition at line 96 of file basic_rf.c.
.SS "\fBint8\fP \fBbasicRfRxInfo_t.length\fP"
.PP
Definition at line 92 of file basic_rf.c.
.SS "\fBuint8\fP* \fBbasicRfRxInfo_t.pPayload\fP"
.PP
Definition at line 93 of file basic_rf.c.
.SS "\fBint8\fP \fBbasicRfRxInfo_t.rssi\fP"
.PP
Definition at line 95 of file basic_rf.c.
.SS "\fBuint8\fP \fBbasicRfRxInfo_t.seqNumber\fP"
.PP
Definition at line 89 of file basic_rf.c.
.SS "\fBuint16\fP \fBbasicRfRxInfo_t.srcAddr\fP"
.PP
Definition at line 90 of file basic_rf.c.
.SS "\fBuint16\fP \fBbasicRfRxInfo_t.srcPanId\fP"
.PP
Definition at line 91 of file basic_rf.c.
.SS "\fBuint8\fP \fBbasicRfRxInfo_t.status\fP"
.PP
Definition at line 97 of file basic_rf.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for Embedded GarageBand from the source code.
