.TH "digioConfig" 3 "Sat Apr 30 2011" "Version 1.0" "Embedded GarageBand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
digioConfig \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hal_digio.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint8\fP \fBport\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBpin\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBpin_bm\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBdir\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBinitval\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 42 of file hal_digio.h.
.SH "Field Documentation"
.PP 
.SS "\fBuint8\fP \fBdigioConfig.dir\fP"
.PP
Definition at line 46 of file hal_digio.h.
.SS "\fBuint8\fP \fBdigioConfig.initval\fP"
.PP
Definition at line 47 of file hal_digio.h.
.SS "\fBuint8\fP \fBdigioConfig.pin\fP"
.PP
Definition at line 44 of file hal_digio.h.
.SS "\fBuint8\fP \fBdigioConfig.pin_bm\fP"
.PP
Definition at line 45 of file hal_digio.h.
.SS "\fBuint8\fP \fBdigioConfig.port\fP"
.PP
Definition at line 43 of file hal_digio.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Embedded GarageBand from the source code.
