.TH "hal_types.h" 3 "Sat Apr 30 2011" "Version 1.0" "Embedded GarageBand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hal_types.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdbool.h>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef signed char \fBint8\fP"
.br
.ti -1c
.RI "typedef unsigned char \fBuint8\fP"
.br
.ti -1c
.RI "typedef signed short \fBint16\fP"
.br
.ti -1c
.RI "typedef unsigned short \fBuint16\fP"
.br
.ti -1c
.RI "typedef signed long \fBint32\fP"
.br
.ti -1c
.RI "typedef unsigned long \fBuint32\fP"
.br
.ti -1c
.RI "typedef void(* \fBISR_FUNC_PTR\fP )(void)"
.br
.ti -1c
.RI "typedef void(* \fBVFPTR\fP )(void)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef signed short \fBint16\fP"
.PP
Definition at line 20 of file hal_types.h.
.SS "typedef signed long \fBint32\fP"
.PP
Definition at line 23 of file hal_types.h.
.SS "typedef signed char \fBint8\fP"
.PP
Definition at line 17 of file hal_types.h.
.SS "typedef void(* \fBISR_FUNC_PTR\fP)(void)"
.PP
Definition at line 27 of file hal_types.h.
.SS "typedef unsigned short \fBuint16\fP"
.PP
Definition at line 21 of file hal_types.h.
.SS "typedef unsigned long \fBuint32\fP"
.PP
Definition at line 24 of file hal_types.h.
.SS "typedef unsigned char \fBuint8\fP"
.PP
Definition at line 18 of file hal_types.h.
.SS "typedef void(* \fBVFPTR\fP)(void)"
.PP
Definition at line 28 of file hal_types.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for Embedded GarageBand from the source code.
