.TH "Loc_DataPayload" 3 "Sat Apr 30 2011" "Version 1.0" "Embedded GarageBand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Loc_DataPayload \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <App_RF.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint8\fP \fBX_Coord\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBY_Coord\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBBlind_Node\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 52 of file App_RF.h.
.SH "Field Documentation"
.PP 
.SS "\fBuint8\fP \fBLoc_DataPayload.Blind_Node\fP"
.PP
Definition at line 55 of file App_RF.h.
.SS "\fBuint8\fP \fBLoc_DataPayload.X_Coord\fP"
.PP
Definition at line 53 of file App_RF.h.
.SS "\fBuint8\fP \fBLoc_DataPayload.Y_Coord\fP"
.PP
Definition at line 54 of file App_RF.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Embedded GarageBand from the source code.
