.TH "menu_t" 3 "Sat Apr 30 2011" "Version 1.0" "Embedded GarageBand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
menu_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <util.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBmenuItem_t\fP * \fBpMenuItems\fP"
.br
.ti -1c
.RI "const \fBuint8\fP \fBnItems\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file util.h.
.SH "Field Documentation"
.PP 
.SS "const \fBuint8\fP \fBmenu_t.nItems\fP"
.PP
Definition at line 28 of file util.h.
.SS "const \fBmenuItem_t\fP* \fBmenu_t.pMenuItems\fP"
.PP
Definition at line 27 of file util.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Embedded GarageBand from the source code.
