.TH "menuItem_t" 3 "Sat Apr 30 2011" "Version 1.0" "Embedded GarageBand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
menuItem_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <util.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBszDescr\fP"
.br
.ti -1c
.RI "const \fBuint8\fP \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file util.h.
.SH "Field Documentation"
.PP 
.SS "const char* \fBmenuItem_t.szDescr\fP"
.PP
Definition at line 22 of file util.h.
.SS "const \fBuint8\fP \fBmenuItem_t.value\fP"
.PP
Definition at line 23 of file util.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Embedded GarageBand from the source code.
