.TH "Project.h" 3 "Sat Apr 30 2011" "Version 1.0" "Embedded GarageBand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Project.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ioCC2431.h>\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include '../Drivers/adc.h'\fP
.br
\fC#include '../Drivers/clock.h'\fP
.br
\fC#include '../Drivers/hal_digio.h'\fP
.br
\fC#include '../Drivers/hal_int.h'\fP
.br
\fC#include '../Drivers/hal_mcu.h'\fP
.br
\fC#include '../Drivers/hal_rf.h'\fP
.br
\fC#include '../Drivers/hal_rf_security.h'\fP
.br
\fC#include '../Drivers/hal_timer_32k.h'\fP
.br
\fC#include '../Interface/basic_rf.h'\fP
.br
\fC#include '../Interface/basic_rf_security.h'\fP
.br
\fC#include '../Interface/hal_assert.h'\fP
.br
\fC#include '../Interface/hal_board.h'\fP
.br
\fC#include '../Interface/hal_button.h'\fP
.br
\fC#include '../Interface/hal_led.h'\fP
.br
\fC#include '../Interface/util.h'\fP
.br
\fC#include '../Interface/util_buffer.h'\fP
.br
\fC#include '../Interface/TouchScreen.h'\fP
.br
\fC#include 'Common/hal_types.h'\fP
.br
\fC#include 'Common/hal_defs.h'\fP
.br
\fC#include 'Common/hal_cc8051.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Embedded GarageBand from the source code.
