.TH "scancodes.h" 3 "Sat Apr 30 2011" "Version 1.0" "Embedded GarageBand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scancodes.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const unsigned char \fBunshifted\fP [][2]"
.br
.ti -1c
.RI "const unsigned char \fBshifted\fP [][2]"
.br
.ti -1c
.RI "const unsigned char \fBspecial\fP [][2]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const unsigned char \fBshifted\fP[][2]"
.PP
Definition at line 84 of file scancodes.h.
.SS "const unsigned char \fBspecial\fP[][2]"\fBInitial value:\fP
.PP
.nf
 {
0x75,1,
0x6B,2,
0x72,3,
0x74,4,
0x4a,'/',
0x5a,13,
0,0
}
.fi
.PP
Definition at line 155 of file scancodes.h.
.SS "const unsigned char \fBunshifted\fP[][2]"
.PP
Definition at line 12 of file scancodes.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for Embedded GarageBand from the source code.
