.TH "TimerInst" 3 "Sat Apr 30 2011" "Version 1.0" "Embedded GarageBand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TimerInst \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint16\fP \fBRequired_Period_Sec\fP"
.br
.ti -1c
.RI "\fBTimerExpiredCallback\fP \fBCallback\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file TimerManager.c.
.SH "Field Documentation"
.PP 
.SS "\fBTimerExpiredCallback\fP \fBTimerInst.Callback\fP"
.PP
Definition at line 38 of file TimerManager.c.
.SS "\fBuint16\fP \fBTimerInst.Required_Period_Sec\fP"
.PP
Definition at line 37 of file TimerManager.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for Embedded GarageBand from the source code.
